### ISSUE TITLE
Vprašanje #1

### ISSUE THREAD

**Issue by TInkara25** [TInkara25/computing_optimal_islands#1]
Pozdravljeni,

do zdaj sva uspela napisati kodo za iskanje praznih (legalnih) trikotnikov na množici točk, naletela pa sva na težavo pri dodajanju povezav k tem trikotnikom, torej pri iskanju večkotnikov.

Trenutno najina funkcija maximalni_veckotniki(points) vrne maksimalno ploščino 4-kotnikov in ne veva, kako bi iz tega prišla do maksimalnega večkotnika.

Hvala za vašo pomoč in lep pozdrav,

Matevž Kopač in Tinkara Žitko.

**Comment by jaanos** [comment]
Nisem čisto prepričan, kako naj bi deloval pristop z dinamičnim programiranjem, ki ga je predlagal prof. Cabello (morda najbolje, da se obrneta kar nanj), ampak iz vajine kode mi ne izgleda, kot da gre za dinamično programiranje. Najverjetneje pa bo treba na pameten način najprej generirati štirikotnike, nato petkotnike, šestkotnike, itd.

Sicer pa, če dodajata trikotnik `xyz` h konveksnemu mnogokotniku, ki ima na svojem robu zaporedoma točke `axyb` (v nasprotni smeri urinega kazalca), bo potrebno preveriti, da sta `axz` in `zyb` leva zavoja. To preverjata s funkcijo `ustrezna_tocka`, ki pa je zaradi uporabe deljenja lahko numerično nestabilna. Bolje bo, če jo prepišeta tako, da se deljenju izogneta, npr.
```python
def ustrezna_tocka(a, b, c):
    ax, ay = a
    bx, by = b
    cx, cy = c
    return ax * (cy - by) + bx * (ay - cy) + cx * (by - ay) >= 0
```

Mimogrede, opazil sem še tole:

https://github.com/TInkara25/computing_optimal_islands/blob/f438d90f801d310608bc0ca22ffeca74fcd34f08/computing.optimal.islands.py#L141

Primerjava s `True` je nepotrebna, saj ima že rezultat klicane funkcije ustrezno vrednost. Če uporabita `or` med seznamoma, bo izraz v oklepajih logična vrednost (`True`, ker sta seznama neprazna). Če želita preveriti, ali je vsaj ena od trojic v seznamu, naredita tako:

```python
    if ustrezna_tocka(b,c,j) and ([a, c, j] in trikotniki or [a, j, c] in trikotniki): 
```
